version: "3.9"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data/
  web:
    container_name: django-container
    build: .
    command: 
      bash -c "sleep 10 &&
      python manage.py sqlmigrate polls 0001 &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db    

volumes:
  pgdata: